package eclipse;

import java.util.Date;

public class QrRecordLog extends BaseObj{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.id
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.cinvcode
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String cinvcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.cinvname
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String cinvname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.opt_time
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private Date optTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.string1
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String string1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.string2
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String string2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.string3
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String string3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.string4
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String string4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.string5
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String string5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.string6
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String string6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.whcode
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String whcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.qrcode
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String qrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.total
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private Integer total;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.qr_record_log.zhai_yao
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	private String zhaiYao;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.id
	 * @return  the value of dbo.qr_record_log.id
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.id
	 * @param id  the value for dbo.qr_record_log.id
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.cinvcode
	 * @return  the value of dbo.qr_record_log.cinvcode
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getCinvcode() {
		return cinvcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.cinvcode
	 * @param cinvcode  the value for dbo.qr_record_log.cinvcode
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setCinvcode(String cinvcode) {
		this.cinvcode = cinvcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.cinvname
	 * @return  the value of dbo.qr_record_log.cinvname
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getCinvname() {
		return cinvname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.cinvname
	 * @param cinvname  the value for dbo.qr_record_log.cinvname
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setCinvname(String cinvname) {
		this.cinvname = cinvname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.opt_time
	 * @return  the value of dbo.qr_record_log.opt_time
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public Date getOptTime() {
		return optTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.opt_time
	 * @param optTime  the value for dbo.qr_record_log.opt_time
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setOptTime(Date optTime) {
		this.optTime = optTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.string1
	 * @return  the value of dbo.qr_record_log.string1
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getString1() {
		return string1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.string1
	 * @param string1  the value for dbo.qr_record_log.string1
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setString1(String string1) {
		this.string1 = string1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.string2
	 * @return  the value of dbo.qr_record_log.string2
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getString2() {
		return string2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.string2
	 * @param string2  the value for dbo.qr_record_log.string2
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setString2(String string2) {
		this.string2 = string2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.string3
	 * @return  the value of dbo.qr_record_log.string3
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getString3() {
		return string3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.string3
	 * @param string3  the value for dbo.qr_record_log.string3
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setString3(String string3) {
		this.string3 = string3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.string4
	 * @return  the value of dbo.qr_record_log.string4
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getString4() {
		return string4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.string4
	 * @param string4  the value for dbo.qr_record_log.string4
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setString4(String string4) {
		this.string4 = string4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.string5
	 * @return  the value of dbo.qr_record_log.string5
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getString5() {
		return string5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.string5
	 * @param string5  the value for dbo.qr_record_log.string5
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setString5(String string5) {
		this.string5 = string5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.string6
	 * @return  the value of dbo.qr_record_log.string6
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getString6() {
		return string6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.string6
	 * @param string6  the value for dbo.qr_record_log.string6
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setString6(String string6) {
		this.string6 = string6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.whcode
	 * @return  the value of dbo.qr_record_log.whcode
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getWhcode() {
		return whcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.whcode
	 * @param whcode  the value for dbo.qr_record_log.whcode
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setWhcode(String whcode) {
		this.whcode = whcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.qrcode
	 * @return  the value of dbo.qr_record_log.qrcode
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getQrcode() {
		return qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.qrcode
	 * @param qrcode  the value for dbo.qr_record_log.qrcode
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.total
	 * @return  the value of dbo.qr_record_log.total
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public Integer getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.total
	 * @param total  the value for dbo.qr_record_log.total
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setTotal(Integer total) {
		this.total = total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.qr_record_log.zhai_yao
	 * @return  the value of dbo.qr_record_log.zhai_yao
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public String getZhaiYao() {
		return zhaiYao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.qr_record_log.zhai_yao
	 * @param zhaiYao  the value for dbo.qr_record_log.zhai_yao
	 * @mbggenerated  Sun Nov 01 23:22:42 CST 2015
	 */
	public void setZhaiYao(String zhaiYao) {
		this.zhaiYao = zhaiYao;
	}
}