package eclipse;

import java.math.BigDecimal;
import java.util.Date;

public class Rdrecords extends BaseObj{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.AutoID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer autoid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.ID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cInvCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cinvcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double inum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double iquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iUnitCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double iunitcost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal iprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iAPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal iaprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iPUnitCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double ipunitcost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iPPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal ipprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cBatch
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cbatch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cObjCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cobjcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cVouchCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cvouchcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree1
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree2
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iFlag
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Byte iflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.dSDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Date dsdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iTax
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal itax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iSQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double isquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iSNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double isnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iMoney
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal imoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iSOutQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double isoutquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iSOutNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double isoutnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iFNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double ifnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iFQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double ifquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.dVDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Date dvdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iTrIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer itrids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cPosition
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cposition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine22
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine22;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine23
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine23;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine24
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine24;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine25
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine25;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine26
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double cdefine26;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine27
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double cdefine27;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cItem_class
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String citemClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cItemCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String citemcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iPOsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer iposid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.fACost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double facost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iDLsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer idlsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iSBsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer isbsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iSendQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double isendquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iSendNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double isendnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cName
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cItemCName
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String citemcname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iEnsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer iensid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree3
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree4
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree5
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree6
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree7
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree8
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree9
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cFree10
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cfree10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cBarCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cbarcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iNQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double inquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iNNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double innum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cAssUnit
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cassunit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.dMadeDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Date dmadedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iMassDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer imassdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine28
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine28;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine29
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine29;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine30
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine30;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine31
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine31;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine32
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine32;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine33
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cdefine33;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine34
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer cdefine34;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine35
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer cdefine35;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine36
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Date cdefine36;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cDefine37
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Date cdefine37;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iMPoIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer impoids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iCheckIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer icheckids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cBVencode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cbvencode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cInVouchCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cinvouchcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.bGsp
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Boolean bgsp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cGspState
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cgspstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iArrsId
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer iarrsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cCheckCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String ccheckcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iCheckIdBaks
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer icheckidbaks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cRejectCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String crejectcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iRejectIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer irejectids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cCheckPersonCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String ccheckpersoncode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.dCheckDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Date dcheckdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iTookQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal itookquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iInvalidQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal iinvalidquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iOMMPoIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer iommpoids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iPBVQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double ipbvquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iPBVyQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double ipbvyquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iBalance
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer ibalance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iHXQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal ihxquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cCAItemCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String ccaitemcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cCBGJDXCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String ccbgjdxcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.bfilled
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer bfilled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iarrptrintype
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer iarrptrintype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.ichkautoid
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer ichkautoid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.irejid
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Integer irejid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.crejtext
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String crejtext;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iTaxCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double itaxcost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iTaxPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double itaxprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iTaxRate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double itaxrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iSum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double isum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iATaxCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double iataxcost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iATaxPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double iataxprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iATaxRate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double iataxrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.iASum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private Double iasum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.MakePrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal makeprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.MakeMny
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal makemny;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.HadBalanceQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal hadbalancequantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.HadBalanceMny
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal hadbalancemny;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.OrgMakePrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private BigDecimal orgmakeprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.cBOMSoCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String cbomsocode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.csocode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String csocode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecords.ccbgjdxname
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	private String ccbgjdxname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.AutoID
	 * @return  the value of RdRecords.AutoID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getAutoid() {
		return autoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.AutoID
	 * @param autoid  the value for RdRecords.AutoID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setAutoid(Integer autoid) {
		this.autoid = autoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.ID
	 * @return  the value of RdRecords.ID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.ID
	 * @param id  the value for RdRecords.ID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cInvCode
	 * @return  the value of RdRecords.cInvCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCinvcode() {
		return cinvcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cInvCode
	 * @param cinvcode  the value for RdRecords.cInvCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCinvcode(String cinvcode) {
		this.cinvcode = cinvcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iNum
	 * @return  the value of RdRecords.iNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getInum() {
		return inum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iNum
	 * @param inum  the value for RdRecords.iNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setInum(Double inum) {
		this.inum = inum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iQuantity
	 * @return  the value of RdRecords.iQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIquantity() {
		return iquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iQuantity
	 * @param iquantity  the value for RdRecords.iQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIquantity(Double iquantity) {
		this.iquantity = iquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iUnitCost
	 * @return  the value of RdRecords.iUnitCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIunitcost() {
		return iunitcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iUnitCost
	 * @param iunitcost  the value for RdRecords.iUnitCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIunitcost(Double iunitcost) {
		this.iunitcost = iunitcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iPrice
	 * @return  the value of RdRecords.iPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getIprice() {
		return iprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iPrice
	 * @param iprice  the value for RdRecords.iPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIprice(BigDecimal iprice) {
		this.iprice = iprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iAPrice
	 * @return  the value of RdRecords.iAPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getIaprice() {
		return iaprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iAPrice
	 * @param iaprice  the value for RdRecords.iAPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIaprice(BigDecimal iaprice) {
		this.iaprice = iaprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iPUnitCost
	 * @return  the value of RdRecords.iPUnitCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIpunitcost() {
		return ipunitcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iPUnitCost
	 * @param ipunitcost  the value for RdRecords.iPUnitCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIpunitcost(Double ipunitcost) {
		this.ipunitcost = ipunitcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iPPrice
	 * @return  the value of RdRecords.iPPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getIpprice() {
		return ipprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iPPrice
	 * @param ipprice  the value for RdRecords.iPPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIpprice(BigDecimal ipprice) {
		this.ipprice = ipprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cBatch
	 * @return  the value of RdRecords.cBatch
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCbatch() {
		return cbatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cBatch
	 * @param cbatch  the value for RdRecords.cBatch
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCbatch(String cbatch) {
		this.cbatch = cbatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cObjCode
	 * @return  the value of RdRecords.cObjCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCobjcode() {
		return cobjcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cObjCode
	 * @param cobjcode  the value for RdRecords.cObjCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCobjcode(String cobjcode) {
		this.cobjcode = cobjcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cVouchCode
	 * @return  the value of RdRecords.cVouchCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCvouchcode() {
		return cvouchcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cVouchCode
	 * @param cvouchcode  the value for RdRecords.cVouchCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCvouchcode(String cvouchcode) {
		this.cvouchcode = cvouchcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree1
	 * @return  the value of RdRecords.cFree1
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree1() {
		return cfree1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree1
	 * @param cfree1  the value for RdRecords.cFree1
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree1(String cfree1) {
		this.cfree1 = cfree1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree2
	 * @return  the value of RdRecords.cFree2
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree2() {
		return cfree2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree2
	 * @param cfree2  the value for RdRecords.cFree2
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree2(String cfree2) {
		this.cfree2 = cfree2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iFlag
	 * @return  the value of RdRecords.iFlag
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Byte getIflag() {
		return iflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iFlag
	 * @param iflag  the value for RdRecords.iFlag
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIflag(Byte iflag) {
		this.iflag = iflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.dSDate
	 * @return  the value of RdRecords.dSDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Date getDsdate() {
		return dsdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.dSDate
	 * @param dsdate  the value for RdRecords.dSDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setDsdate(Date dsdate) {
		this.dsdate = dsdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iTax
	 * @return  the value of RdRecords.iTax
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getItax() {
		return itax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iTax
	 * @param itax  the value for RdRecords.iTax
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setItax(BigDecimal itax) {
		this.itax = itax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iSQuantity
	 * @return  the value of RdRecords.iSQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIsquantity() {
		return isquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iSQuantity
	 * @param isquantity  the value for RdRecords.iSQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIsquantity(Double isquantity) {
		this.isquantity = isquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iSNum
	 * @return  the value of RdRecords.iSNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIsnum() {
		return isnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iSNum
	 * @param isnum  the value for RdRecords.iSNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIsnum(Double isnum) {
		this.isnum = isnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iMoney
	 * @return  the value of RdRecords.iMoney
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getImoney() {
		return imoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iMoney
	 * @param imoney  the value for RdRecords.iMoney
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setImoney(BigDecimal imoney) {
		this.imoney = imoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iSOutQuantity
	 * @return  the value of RdRecords.iSOutQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIsoutquantity() {
		return isoutquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iSOutQuantity
	 * @param isoutquantity  the value for RdRecords.iSOutQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIsoutquantity(Double isoutquantity) {
		this.isoutquantity = isoutquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iSOutNum
	 * @return  the value of RdRecords.iSOutNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIsoutnum() {
		return isoutnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iSOutNum
	 * @param isoutnum  the value for RdRecords.iSOutNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIsoutnum(Double isoutnum) {
		this.isoutnum = isoutnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iFNum
	 * @return  the value of RdRecords.iFNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIfnum() {
		return ifnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iFNum
	 * @param ifnum  the value for RdRecords.iFNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIfnum(Double ifnum) {
		this.ifnum = ifnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iFQuantity
	 * @return  the value of RdRecords.iFQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIfquantity() {
		return ifquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iFQuantity
	 * @param ifquantity  the value for RdRecords.iFQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIfquantity(Double ifquantity) {
		this.ifquantity = ifquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.dVDate
	 * @return  the value of RdRecords.dVDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Date getDvdate() {
		return dvdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.dVDate
	 * @param dvdate  the value for RdRecords.dVDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setDvdate(Date dvdate) {
		this.dvdate = dvdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iTrIds
	 * @return  the value of RdRecords.iTrIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getItrids() {
		return itrids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iTrIds
	 * @param itrids  the value for RdRecords.iTrIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setItrids(Integer itrids) {
		this.itrids = itrids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cPosition
	 * @return  the value of RdRecords.cPosition
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCposition() {
		return cposition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cPosition
	 * @param cposition  the value for RdRecords.cPosition
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCposition(String cposition) {
		this.cposition = cposition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine22
	 * @return  the value of RdRecords.cDefine22
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine22() {
		return cdefine22;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine22
	 * @param cdefine22  the value for RdRecords.cDefine22
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine22(String cdefine22) {
		this.cdefine22 = cdefine22;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine23
	 * @return  the value of RdRecords.cDefine23
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine23() {
		return cdefine23;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine23
	 * @param cdefine23  the value for RdRecords.cDefine23
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine23(String cdefine23) {
		this.cdefine23 = cdefine23;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine24
	 * @return  the value of RdRecords.cDefine24
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine24() {
		return cdefine24;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine24
	 * @param cdefine24  the value for RdRecords.cDefine24
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine24(String cdefine24) {
		this.cdefine24 = cdefine24;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine25
	 * @return  the value of RdRecords.cDefine25
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine25() {
		return cdefine25;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine25
	 * @param cdefine25  the value for RdRecords.cDefine25
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine25(String cdefine25) {
		this.cdefine25 = cdefine25;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine26
	 * @return  the value of RdRecords.cDefine26
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getCdefine26() {
		return cdefine26;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine26
	 * @param cdefine26  the value for RdRecords.cDefine26
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine26(Double cdefine26) {
		this.cdefine26 = cdefine26;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine27
	 * @return  the value of RdRecords.cDefine27
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getCdefine27() {
		return cdefine27;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine27
	 * @param cdefine27  the value for RdRecords.cDefine27
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine27(Double cdefine27) {
		this.cdefine27 = cdefine27;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cItem_class
	 * @return  the value of RdRecords.cItem_class
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCitemClass() {
		return citemClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cItem_class
	 * @param citemClass  the value for RdRecords.cItem_class
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCitemClass(String citemClass) {
		this.citemClass = citemClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cItemCode
	 * @return  the value of RdRecords.cItemCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCitemcode() {
		return citemcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cItemCode
	 * @param citemcode  the value for RdRecords.cItemCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCitemcode(String citemcode) {
		this.citemcode = citemcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iPOsID
	 * @return  the value of RdRecords.iPOsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIposid() {
		return iposid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iPOsID
	 * @param iposid  the value for RdRecords.iPOsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIposid(Integer iposid) {
		this.iposid = iposid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.fACost
	 * @return  the value of RdRecords.fACost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getFacost() {
		return facost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.fACost
	 * @param facost  the value for RdRecords.fACost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setFacost(Double facost) {
		this.facost = facost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iDLsID
	 * @return  the value of RdRecords.iDLsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIdlsid() {
		return idlsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iDLsID
	 * @param idlsid  the value for RdRecords.iDLsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIdlsid(Integer idlsid) {
		this.idlsid = idlsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iSBsID
	 * @return  the value of RdRecords.iSBsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIsbsid() {
		return isbsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iSBsID
	 * @param isbsid  the value for RdRecords.iSBsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIsbsid(Integer isbsid) {
		this.isbsid = isbsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iSendQuantity
	 * @return  the value of RdRecords.iSendQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIsendquantity() {
		return isendquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iSendQuantity
	 * @param isendquantity  the value for RdRecords.iSendQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIsendquantity(Double isendquantity) {
		this.isendquantity = isendquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iSendNum
	 * @return  the value of RdRecords.iSendNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIsendnum() {
		return isendnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iSendNum
	 * @param isendnum  the value for RdRecords.iSendNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIsendnum(Double isendnum) {
		this.isendnum = isendnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cName
	 * @return  the value of RdRecords.cName
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cName
	 * @param cname  the value for RdRecords.cName
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCname(String cname) {
		this.cname = cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cItemCName
	 * @return  the value of RdRecords.cItemCName
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCitemcname() {
		return citemcname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cItemCName
	 * @param citemcname  the value for RdRecords.cItemCName
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCitemcname(String citemcname) {
		this.citemcname = citemcname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iEnsID
	 * @return  the value of RdRecords.iEnsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIensid() {
		return iensid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iEnsID
	 * @param iensid  the value for RdRecords.iEnsID
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIensid(Integer iensid) {
		this.iensid = iensid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree3
	 * @return  the value of RdRecords.cFree3
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree3() {
		return cfree3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree3
	 * @param cfree3  the value for RdRecords.cFree3
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree3(String cfree3) {
		this.cfree3 = cfree3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree4
	 * @return  the value of RdRecords.cFree4
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree4() {
		return cfree4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree4
	 * @param cfree4  the value for RdRecords.cFree4
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree4(String cfree4) {
		this.cfree4 = cfree4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree5
	 * @return  the value of RdRecords.cFree5
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree5() {
		return cfree5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree5
	 * @param cfree5  the value for RdRecords.cFree5
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree5(String cfree5) {
		this.cfree5 = cfree5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree6
	 * @return  the value of RdRecords.cFree6
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree6() {
		return cfree6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree6
	 * @param cfree6  the value for RdRecords.cFree6
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree6(String cfree6) {
		this.cfree6 = cfree6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree7
	 * @return  the value of RdRecords.cFree7
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree7() {
		return cfree7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree7
	 * @param cfree7  the value for RdRecords.cFree7
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree7(String cfree7) {
		this.cfree7 = cfree7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree8
	 * @return  the value of RdRecords.cFree8
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree8() {
		return cfree8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree8
	 * @param cfree8  the value for RdRecords.cFree8
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree8(String cfree8) {
		this.cfree8 = cfree8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree9
	 * @return  the value of RdRecords.cFree9
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree9() {
		return cfree9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree9
	 * @param cfree9  the value for RdRecords.cFree9
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree9(String cfree9) {
		this.cfree9 = cfree9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cFree10
	 * @return  the value of RdRecords.cFree10
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCfree10() {
		return cfree10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cFree10
	 * @param cfree10  the value for RdRecords.cFree10
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCfree10(String cfree10) {
		this.cfree10 = cfree10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cBarCode
	 * @return  the value of RdRecords.cBarCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCbarcode() {
		return cbarcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cBarCode
	 * @param cbarcode  the value for RdRecords.cBarCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCbarcode(String cbarcode) {
		this.cbarcode = cbarcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iNQuantity
	 * @return  the value of RdRecords.iNQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getInquantity() {
		return inquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iNQuantity
	 * @param inquantity  the value for RdRecords.iNQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setInquantity(Double inquantity) {
		this.inquantity = inquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iNNum
	 * @return  the value of RdRecords.iNNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getInnum() {
		return innum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iNNum
	 * @param innum  the value for RdRecords.iNNum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setInnum(Double innum) {
		this.innum = innum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cAssUnit
	 * @return  the value of RdRecords.cAssUnit
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCassunit() {
		return cassunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cAssUnit
	 * @param cassunit  the value for RdRecords.cAssUnit
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCassunit(String cassunit) {
		this.cassunit = cassunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.dMadeDate
	 * @return  the value of RdRecords.dMadeDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Date getDmadedate() {
		return dmadedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.dMadeDate
	 * @param dmadedate  the value for RdRecords.dMadeDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setDmadedate(Date dmadedate) {
		this.dmadedate = dmadedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iMassDate
	 * @return  the value of RdRecords.iMassDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getImassdate() {
		return imassdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iMassDate
	 * @param imassdate  the value for RdRecords.iMassDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setImassdate(Integer imassdate) {
		this.imassdate = imassdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine28
	 * @return  the value of RdRecords.cDefine28
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine28() {
		return cdefine28;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine28
	 * @param cdefine28  the value for RdRecords.cDefine28
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine28(String cdefine28) {
		this.cdefine28 = cdefine28;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine29
	 * @return  the value of RdRecords.cDefine29
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine29() {
		return cdefine29;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine29
	 * @param cdefine29  the value for RdRecords.cDefine29
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine29(String cdefine29) {
		this.cdefine29 = cdefine29;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine30
	 * @return  the value of RdRecords.cDefine30
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine30() {
		return cdefine30;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine30
	 * @param cdefine30  the value for RdRecords.cDefine30
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine30(String cdefine30) {
		this.cdefine30 = cdefine30;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine31
	 * @return  the value of RdRecords.cDefine31
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine31() {
		return cdefine31;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine31
	 * @param cdefine31  the value for RdRecords.cDefine31
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine31(String cdefine31) {
		this.cdefine31 = cdefine31;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine32
	 * @return  the value of RdRecords.cDefine32
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine32() {
		return cdefine32;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine32
	 * @param cdefine32  the value for RdRecords.cDefine32
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine32(String cdefine32) {
		this.cdefine32 = cdefine32;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine33
	 * @return  the value of RdRecords.cDefine33
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCdefine33() {
		return cdefine33;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine33
	 * @param cdefine33  the value for RdRecords.cDefine33
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine33(String cdefine33) {
		this.cdefine33 = cdefine33;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine34
	 * @return  the value of RdRecords.cDefine34
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getCdefine34() {
		return cdefine34;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine34
	 * @param cdefine34  the value for RdRecords.cDefine34
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine34(Integer cdefine34) {
		this.cdefine34 = cdefine34;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine35
	 * @return  the value of RdRecords.cDefine35
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getCdefine35() {
		return cdefine35;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine35
	 * @param cdefine35  the value for RdRecords.cDefine35
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine35(Integer cdefine35) {
		this.cdefine35 = cdefine35;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine36
	 * @return  the value of RdRecords.cDefine36
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Date getCdefine36() {
		return cdefine36;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine36
	 * @param cdefine36  the value for RdRecords.cDefine36
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine36(Date cdefine36) {
		this.cdefine36 = cdefine36;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cDefine37
	 * @return  the value of RdRecords.cDefine37
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Date getCdefine37() {
		return cdefine37;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cDefine37
	 * @param cdefine37  the value for RdRecords.cDefine37
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCdefine37(Date cdefine37) {
		this.cdefine37 = cdefine37;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iMPoIds
	 * @return  the value of RdRecords.iMPoIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getImpoids() {
		return impoids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iMPoIds
	 * @param impoids  the value for RdRecords.iMPoIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setImpoids(Integer impoids) {
		this.impoids = impoids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iCheckIds
	 * @return  the value of RdRecords.iCheckIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIcheckids() {
		return icheckids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iCheckIds
	 * @param icheckids  the value for RdRecords.iCheckIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIcheckids(Integer icheckids) {
		this.icheckids = icheckids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cBVencode
	 * @return  the value of RdRecords.cBVencode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCbvencode() {
		return cbvencode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cBVencode
	 * @param cbvencode  the value for RdRecords.cBVencode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCbvencode(String cbvencode) {
		this.cbvencode = cbvencode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cInVouchCode
	 * @return  the value of RdRecords.cInVouchCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCinvouchcode() {
		return cinvouchcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cInVouchCode
	 * @param cinvouchcode  the value for RdRecords.cInVouchCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCinvouchcode(String cinvouchcode) {
		this.cinvouchcode = cinvouchcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.bGsp
	 * @return  the value of RdRecords.bGsp
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Boolean getBgsp() {
		return bgsp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.bGsp
	 * @param bgsp  the value for RdRecords.bGsp
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setBgsp(Boolean bgsp) {
		this.bgsp = bgsp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cGspState
	 * @return  the value of RdRecords.cGspState
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCgspstate() {
		return cgspstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cGspState
	 * @param cgspstate  the value for RdRecords.cGspState
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCgspstate(String cgspstate) {
		this.cgspstate = cgspstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iArrsId
	 * @return  the value of RdRecords.iArrsId
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIarrsid() {
		return iarrsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iArrsId
	 * @param iarrsid  the value for RdRecords.iArrsId
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIarrsid(Integer iarrsid) {
		this.iarrsid = iarrsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cCheckCode
	 * @return  the value of RdRecords.cCheckCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCcheckcode() {
		return ccheckcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cCheckCode
	 * @param ccheckcode  the value for RdRecords.cCheckCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCcheckcode(String ccheckcode) {
		this.ccheckcode = ccheckcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iCheckIdBaks
	 * @return  the value of RdRecords.iCheckIdBaks
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIcheckidbaks() {
		return icheckidbaks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iCheckIdBaks
	 * @param icheckidbaks  the value for RdRecords.iCheckIdBaks
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIcheckidbaks(Integer icheckidbaks) {
		this.icheckidbaks = icheckidbaks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cRejectCode
	 * @return  the value of RdRecords.cRejectCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCrejectcode() {
		return crejectcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cRejectCode
	 * @param crejectcode  the value for RdRecords.cRejectCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCrejectcode(String crejectcode) {
		this.crejectcode = crejectcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iRejectIds
	 * @return  the value of RdRecords.iRejectIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIrejectids() {
		return irejectids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iRejectIds
	 * @param irejectids  the value for RdRecords.iRejectIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIrejectids(Integer irejectids) {
		this.irejectids = irejectids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cCheckPersonCode
	 * @return  the value of RdRecords.cCheckPersonCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCcheckpersoncode() {
		return ccheckpersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cCheckPersonCode
	 * @param ccheckpersoncode  the value for RdRecords.cCheckPersonCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCcheckpersoncode(String ccheckpersoncode) {
		this.ccheckpersoncode = ccheckpersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.dCheckDate
	 * @return  the value of RdRecords.dCheckDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Date getDcheckdate() {
		return dcheckdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.dCheckDate
	 * @param dcheckdate  the value for RdRecords.dCheckDate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setDcheckdate(Date dcheckdate) {
		this.dcheckdate = dcheckdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iTookQuantity
	 * @return  the value of RdRecords.iTookQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getItookquantity() {
		return itookquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iTookQuantity
	 * @param itookquantity  the value for RdRecords.iTookQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setItookquantity(BigDecimal itookquantity) {
		this.itookquantity = itookquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iInvalidQuantity
	 * @return  the value of RdRecords.iInvalidQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getIinvalidquantity() {
		return iinvalidquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iInvalidQuantity
	 * @param iinvalidquantity  the value for RdRecords.iInvalidQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIinvalidquantity(BigDecimal iinvalidquantity) {
		this.iinvalidquantity = iinvalidquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iOMMPoIds
	 * @return  the value of RdRecords.iOMMPoIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIommpoids() {
		return iommpoids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iOMMPoIds
	 * @param iommpoids  the value for RdRecords.iOMMPoIds
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIommpoids(Integer iommpoids) {
		this.iommpoids = iommpoids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iPBVQuantity
	 * @return  the value of RdRecords.iPBVQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIpbvquantity() {
		return ipbvquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iPBVQuantity
	 * @param ipbvquantity  the value for RdRecords.iPBVQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIpbvquantity(Double ipbvquantity) {
		this.ipbvquantity = ipbvquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iPBVyQuantity
	 * @return  the value of RdRecords.iPBVyQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIpbvyquantity() {
		return ipbvyquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iPBVyQuantity
	 * @param ipbvyquantity  the value for RdRecords.iPBVyQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIpbvyquantity(Double ipbvyquantity) {
		this.ipbvyquantity = ipbvyquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iBalance
	 * @return  the value of RdRecords.iBalance
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIbalance() {
		return ibalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iBalance
	 * @param ibalance  the value for RdRecords.iBalance
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIbalance(Integer ibalance) {
		this.ibalance = ibalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iHXQuantity
	 * @return  the value of RdRecords.iHXQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getIhxquantity() {
		return ihxquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iHXQuantity
	 * @param ihxquantity  the value for RdRecords.iHXQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIhxquantity(BigDecimal ihxquantity) {
		this.ihxquantity = ihxquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cCAItemCode
	 * @return  the value of RdRecords.cCAItemCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCcaitemcode() {
		return ccaitemcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cCAItemCode
	 * @param ccaitemcode  the value for RdRecords.cCAItemCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCcaitemcode(String ccaitemcode) {
		this.ccaitemcode = ccaitemcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cCBGJDXCode
	 * @return  the value of RdRecords.cCBGJDXCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCcbgjdxcode() {
		return ccbgjdxcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cCBGJDXCode
	 * @param ccbgjdxcode  the value for RdRecords.cCBGJDXCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCcbgjdxcode(String ccbgjdxcode) {
		this.ccbgjdxcode = ccbgjdxcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.bfilled
	 * @return  the value of RdRecords.bfilled
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getBfilled() {
		return bfilled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.bfilled
	 * @param bfilled  the value for RdRecords.bfilled
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setBfilled(Integer bfilled) {
		this.bfilled = bfilled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iarrptrintype
	 * @return  the value of RdRecords.iarrptrintype
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIarrptrintype() {
		return iarrptrintype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iarrptrintype
	 * @param iarrptrintype  the value for RdRecords.iarrptrintype
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIarrptrintype(Integer iarrptrintype) {
		this.iarrptrintype = iarrptrintype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.ichkautoid
	 * @return  the value of RdRecords.ichkautoid
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIchkautoid() {
		return ichkautoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.ichkautoid
	 * @param ichkautoid  the value for RdRecords.ichkautoid
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIchkautoid(Integer ichkautoid) {
		this.ichkautoid = ichkautoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.irejid
	 * @return  the value of RdRecords.irejid
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Integer getIrejid() {
		return irejid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.irejid
	 * @param irejid  the value for RdRecords.irejid
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIrejid(Integer irejid) {
		this.irejid = irejid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.crejtext
	 * @return  the value of RdRecords.crejtext
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCrejtext() {
		return crejtext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.crejtext
	 * @param crejtext  the value for RdRecords.crejtext
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCrejtext(String crejtext) {
		this.crejtext = crejtext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iTaxCost
	 * @return  the value of RdRecords.iTaxCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getItaxcost() {
		return itaxcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iTaxCost
	 * @param itaxcost  the value for RdRecords.iTaxCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setItaxcost(Double itaxcost) {
		this.itaxcost = itaxcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iTaxPrice
	 * @return  the value of RdRecords.iTaxPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getItaxprice() {
		return itaxprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iTaxPrice
	 * @param itaxprice  the value for RdRecords.iTaxPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setItaxprice(Double itaxprice) {
		this.itaxprice = itaxprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iTaxRate
	 * @return  the value of RdRecords.iTaxRate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getItaxrate() {
		return itaxrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iTaxRate
	 * @param itaxrate  the value for RdRecords.iTaxRate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setItaxrate(Double itaxrate) {
		this.itaxrate = itaxrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iSum
	 * @return  the value of RdRecords.iSum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIsum() {
		return isum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iSum
	 * @param isum  the value for RdRecords.iSum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIsum(Double isum) {
		this.isum = isum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iATaxCost
	 * @return  the value of RdRecords.iATaxCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIataxcost() {
		return iataxcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iATaxCost
	 * @param iataxcost  the value for RdRecords.iATaxCost
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIataxcost(Double iataxcost) {
		this.iataxcost = iataxcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iATaxPrice
	 * @return  the value of RdRecords.iATaxPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIataxprice() {
		return iataxprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iATaxPrice
	 * @param iataxprice  the value for RdRecords.iATaxPrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIataxprice(Double iataxprice) {
		this.iataxprice = iataxprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iATaxRate
	 * @return  the value of RdRecords.iATaxRate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIataxrate() {
		return iataxrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iATaxRate
	 * @param iataxrate  the value for RdRecords.iATaxRate
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIataxrate(Double iataxrate) {
		this.iataxrate = iataxrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.iASum
	 * @return  the value of RdRecords.iASum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public Double getIasum() {
		return iasum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.iASum
	 * @param iasum  the value for RdRecords.iASum
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setIasum(Double iasum) {
		this.iasum = iasum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.MakePrice
	 * @return  the value of RdRecords.MakePrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getMakeprice() {
		return makeprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.MakePrice
	 * @param makeprice  the value for RdRecords.MakePrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setMakeprice(BigDecimal makeprice) {
		this.makeprice = makeprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.MakeMny
	 * @return  the value of RdRecords.MakeMny
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getMakemny() {
		return makemny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.MakeMny
	 * @param makemny  the value for RdRecords.MakeMny
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setMakemny(BigDecimal makemny) {
		this.makemny = makemny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.HadBalanceQuantity
	 * @return  the value of RdRecords.HadBalanceQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getHadbalancequantity() {
		return hadbalancequantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.HadBalanceQuantity
	 * @param hadbalancequantity  the value for RdRecords.HadBalanceQuantity
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setHadbalancequantity(BigDecimal hadbalancequantity) {
		this.hadbalancequantity = hadbalancequantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.HadBalanceMny
	 * @return  the value of RdRecords.HadBalanceMny
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getHadbalancemny() {
		return hadbalancemny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.HadBalanceMny
	 * @param hadbalancemny  the value for RdRecords.HadBalanceMny
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setHadbalancemny(BigDecimal hadbalancemny) {
		this.hadbalancemny = hadbalancemny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.OrgMakePrice
	 * @return  the value of RdRecords.OrgMakePrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public BigDecimal getOrgmakeprice() {
		return orgmakeprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.OrgMakePrice
	 * @param orgmakeprice  the value for RdRecords.OrgMakePrice
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setOrgmakeprice(BigDecimal orgmakeprice) {
		this.orgmakeprice = orgmakeprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.cBOMSoCode
	 * @return  the value of RdRecords.cBOMSoCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCbomsocode() {
		return cbomsocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.cBOMSoCode
	 * @param cbomsocode  the value for RdRecords.cBOMSoCode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCbomsocode(String cbomsocode) {
		this.cbomsocode = cbomsocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.csocode
	 * @return  the value of RdRecords.csocode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCsocode() {
		return csocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.csocode
	 * @param csocode  the value for RdRecords.csocode
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCsocode(String csocode) {
		this.csocode = csocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecords.ccbgjdxname
	 * @return  the value of RdRecords.ccbgjdxname
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public String getCcbgjdxname() {
		return ccbgjdxname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecords.ccbgjdxname
	 * @param ccbgjdxname  the value for RdRecords.ccbgjdxname
	 * @mbggenerated  Sun Sep 13 16:49:15 CST 2015
	 */
	public void setCcbgjdxname(String ccbgjdxname) {
		this.ccbgjdxname = ccbgjdxname;
	}
}