package eclipse;


import java.util.Date;

public class Rdrecord extends BaseObj{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.ID
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.bRdFlag
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer brdflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cVouchType
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvouchtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cBusType
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cbustype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cSource
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String csource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cBusCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cbuscode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cWhCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cwhcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.dDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Date ddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String ccode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cRdCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String crdcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDepCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdepcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cPersonCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cpersoncode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cPTCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cptcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cSTCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cstcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cCusCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String ccuscode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cVenCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvencode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cOrderCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cordercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cARVCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String carvcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cBillCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer cbillcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDLCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer cdlcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cProBatch
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cprobatch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cHandler
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String chandler;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cMemo
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cmemo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.bTransFlag
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Boolean btransflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cAccounter
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String caccounter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cMaker
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cmaker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.iNetLock
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Float inetlock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine1
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine2
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine3
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine4
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Date cdefine4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine5
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer cdefine5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine6
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Date cdefine6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine7
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Double cdefine7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine8
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine9
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine10
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.dKeepDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String dkeepdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.dVeriDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Date dveridate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.bpufirst
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Boolean bpufirst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.biafirst
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Boolean biafirst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.iMQuantity
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Double imquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.dARVDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Date darvdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cChkCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cchkcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.dChkDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Date dchkdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cChkPerson
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cchkperson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.VT_ID
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer vtId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.bIsSTQc
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Boolean bisstqc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine11
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine11;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine12
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine12;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine13
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine13;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine14
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cdefine14;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine15
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer cdefine15;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cDefine16
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Double cdefine16;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cPsPcode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cpspcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cMPoCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cmpocode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.gspcheck
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String gspcheck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.ipurorderid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer ipurorderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.ipurarriveid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer ipurarriveid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.iproorderid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Integer iproorderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.iarriveid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String iarriveid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.isalebillid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String isalebillid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cBomSoCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cbomsocode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cOMrdType
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String comrdtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cBusCode2
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cbuscode2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.iTaxRate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Double itaxrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cAccountPID
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String caccountpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cAccountPDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Date caccountpdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cPayCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cpaycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.bgxljz
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Boolean bgxljz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.bisomqc
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private Boolean bisomqc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cvenbank
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvenbank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cvenaddress
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvenaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cvenphone
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvenphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cvenfax
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvenfax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cvenpostcode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvenpostcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cvenperson
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvenperson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cvenaccount
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvenaccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.cvenregcode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private String cvenregcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RdRecord.ufts
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	private byte[] ufts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.ID
	 * @return  the value of RdRecord.ID
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.ID
	 * @param id  the value for RdRecord.ID
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.bRdFlag
	 * @return  the value of RdRecord.bRdFlag
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getBrdflag() {
		return brdflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.bRdFlag
	 * @param brdflag  the value for RdRecord.bRdFlag
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setBrdflag(Integer brdflag) {
		this.brdflag = brdflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cVouchType
	 * @return  the value of RdRecord.cVouchType
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvouchtype() {
		return cvouchtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cVouchType
	 * @param cvouchtype  the value for RdRecord.cVouchType
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvouchtype(String cvouchtype) {
		this.cvouchtype = cvouchtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cBusType
	 * @return  the value of RdRecord.cBusType
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCbustype() {
		return cbustype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cBusType
	 * @param cbustype  the value for RdRecord.cBusType
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCbustype(String cbustype) {
		this.cbustype = cbustype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cSource
	 * @return  the value of RdRecord.cSource
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCsource() {
		return csource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cSource
	 * @param csource  the value for RdRecord.cSource
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCsource(String csource) {
		this.csource = csource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cBusCode
	 * @return  the value of RdRecord.cBusCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCbuscode() {
		return cbuscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cBusCode
	 * @param cbuscode  the value for RdRecord.cBusCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCbuscode(String cbuscode) {
		this.cbuscode = cbuscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cWhCode
	 * @return  the value of RdRecord.cWhCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCwhcode() {
		return cwhcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cWhCode
	 * @param cwhcode  the value for RdRecord.cWhCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCwhcode(String cwhcode) {
		this.cwhcode = cwhcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.dDate
	 * @return  the value of RdRecord.dDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Date getDdate() {
		return ddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.dDate
	 * @param ddate  the value for RdRecord.dDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setDdate(Date ddate) {
		this.ddate = ddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cCode
	 * @return  the value of RdRecord.cCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCcode() {
		return ccode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cCode
	 * @param ccode  the value for RdRecord.cCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCcode(String ccode) {
		this.ccode = ccode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cRdCode
	 * @return  the value of RdRecord.cRdCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCrdcode() {
		return crdcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cRdCode
	 * @param crdcode  the value for RdRecord.cRdCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCrdcode(String crdcode) {
		this.crdcode = crdcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDepCode
	 * @return  the value of RdRecord.cDepCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdepcode() {
		return cdepcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDepCode
	 * @param cdepcode  the value for RdRecord.cDepCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdepcode(String cdepcode) {
		this.cdepcode = cdepcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cPersonCode
	 * @return  the value of RdRecord.cPersonCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCpersoncode() {
		return cpersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cPersonCode
	 * @param cpersoncode  the value for RdRecord.cPersonCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCpersoncode(String cpersoncode) {
		this.cpersoncode = cpersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cPTCode
	 * @return  the value of RdRecord.cPTCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCptcode() {
		return cptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cPTCode
	 * @param cptcode  the value for RdRecord.cPTCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCptcode(String cptcode) {
		this.cptcode = cptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cSTCode
	 * @return  the value of RdRecord.cSTCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCstcode() {
		return cstcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cSTCode
	 * @param cstcode  the value for RdRecord.cSTCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCstcode(String cstcode) {
		this.cstcode = cstcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cCusCode
	 * @return  the value of RdRecord.cCusCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCcuscode() {
		return ccuscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cCusCode
	 * @param ccuscode  the value for RdRecord.cCusCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCcuscode(String ccuscode) {
		this.ccuscode = ccuscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cVenCode
	 * @return  the value of RdRecord.cVenCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvencode() {
		return cvencode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cVenCode
	 * @param cvencode  the value for RdRecord.cVenCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvencode(String cvencode) {
		this.cvencode = cvencode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cOrderCode
	 * @return  the value of RdRecord.cOrderCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCordercode() {
		return cordercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cOrderCode
	 * @param cordercode  the value for RdRecord.cOrderCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCordercode(String cordercode) {
		this.cordercode = cordercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cARVCode
	 * @return  the value of RdRecord.cARVCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCarvcode() {
		return carvcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cARVCode
	 * @param carvcode  the value for RdRecord.cARVCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCarvcode(String carvcode) {
		this.carvcode = carvcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cBillCode
	 * @return  the value of RdRecord.cBillCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getCbillcode() {
		return cbillcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cBillCode
	 * @param cbillcode  the value for RdRecord.cBillCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCbillcode(Integer cbillcode) {
		this.cbillcode = cbillcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDLCode
	 * @return  the value of RdRecord.cDLCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getCdlcode() {
		return cdlcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDLCode
	 * @param cdlcode  the value for RdRecord.cDLCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdlcode(Integer cdlcode) {
		this.cdlcode = cdlcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cProBatch
	 * @return  the value of RdRecord.cProBatch
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCprobatch() {
		return cprobatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cProBatch
	 * @param cprobatch  the value for RdRecord.cProBatch
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCprobatch(String cprobatch) {
		this.cprobatch = cprobatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cHandler
	 * @return  the value of RdRecord.cHandler
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getChandler() {
		return chandler;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cHandler
	 * @param chandler  the value for RdRecord.cHandler
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setChandler(String chandler) {
		this.chandler = chandler;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cMemo
	 * @return  the value of RdRecord.cMemo
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCmemo() {
		return cmemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cMemo
	 * @param cmemo  the value for RdRecord.cMemo
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCmemo(String cmemo) {
		this.cmemo = cmemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.bTransFlag
	 * @return  the value of RdRecord.bTransFlag
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Boolean getBtransflag() {
		return btransflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.bTransFlag
	 * @param btransflag  the value for RdRecord.bTransFlag
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setBtransflag(Boolean btransflag) {
		this.btransflag = btransflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cAccounter
	 * @return  the value of RdRecord.cAccounter
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCaccounter() {
		return caccounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cAccounter
	 * @param caccounter  the value for RdRecord.cAccounter
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCaccounter(String caccounter) {
		this.caccounter = caccounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cMaker
	 * @return  the value of RdRecord.cMaker
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCmaker() {
		return cmaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cMaker
	 * @param cmaker  the value for RdRecord.cMaker
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCmaker(String cmaker) {
		this.cmaker = cmaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.iNetLock
	 * @return  the value of RdRecord.iNetLock
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Float getInetlock() {
		return inetlock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.iNetLock
	 * @param inetlock  the value for RdRecord.iNetLock
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setInetlock(Float inetlock) {
		this.inetlock = inetlock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine1
	 * @return  the value of RdRecord.cDefine1
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine1() {
		return cdefine1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine1
	 * @param cdefine1  the value for RdRecord.cDefine1
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine1(String cdefine1) {
		this.cdefine1 = cdefine1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine2
	 * @return  the value of RdRecord.cDefine2
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine2() {
		return cdefine2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine2
	 * @param cdefine2  the value for RdRecord.cDefine2
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine2(String cdefine2) {
		this.cdefine2 = cdefine2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine3
	 * @return  the value of RdRecord.cDefine3
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine3() {
		return cdefine3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine3
	 * @param cdefine3  the value for RdRecord.cDefine3
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine3(String cdefine3) {
		this.cdefine3 = cdefine3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine4
	 * @return  the value of RdRecord.cDefine4
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Date getCdefine4() {
		return cdefine4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine4
	 * @param cdefine4  the value for RdRecord.cDefine4
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine4(Date cdefine4) {
		this.cdefine4 = cdefine4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine5
	 * @return  the value of RdRecord.cDefine5
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getCdefine5() {
		return cdefine5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine5
	 * @param cdefine5  the value for RdRecord.cDefine5
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine5(Integer cdefine5) {
		this.cdefine5 = cdefine5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine6
	 * @return  the value of RdRecord.cDefine6
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Date getCdefine6() {
		return cdefine6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine6
	 * @param cdefine6  the value for RdRecord.cDefine6
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine6(Date cdefine6) {
		this.cdefine6 = cdefine6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine7
	 * @return  the value of RdRecord.cDefine7
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Double getCdefine7() {
		return cdefine7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine7
	 * @param cdefine7  the value for RdRecord.cDefine7
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine7(Double cdefine7) {
		this.cdefine7 = cdefine7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine8
	 * @return  the value of RdRecord.cDefine8
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine8() {
		return cdefine8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine8
	 * @param cdefine8  the value for RdRecord.cDefine8
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine8(String cdefine8) {
		this.cdefine8 = cdefine8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine9
	 * @return  the value of RdRecord.cDefine9
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine9() {
		return cdefine9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine9
	 * @param cdefine9  the value for RdRecord.cDefine9
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine9(String cdefine9) {
		this.cdefine9 = cdefine9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine10
	 * @return  the value of RdRecord.cDefine10
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine10() {
		return cdefine10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine10
	 * @param cdefine10  the value for RdRecord.cDefine10
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine10(String cdefine10) {
		this.cdefine10 = cdefine10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.dKeepDate
	 * @return  the value of RdRecord.dKeepDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getDkeepdate() {
		return dkeepdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.dKeepDate
	 * @param dkeepdate  the value for RdRecord.dKeepDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setDkeepdate(String dkeepdate) {
		this.dkeepdate = dkeepdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.dVeriDate
	 * @return  the value of RdRecord.dVeriDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Date getDveridate() {
		return dveridate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.dVeriDate
	 * @param dveridate  the value for RdRecord.dVeriDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setDveridate(Date dveridate) {
		this.dveridate = dveridate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.bpufirst
	 * @return  the value of RdRecord.bpufirst
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Boolean getBpufirst() {
		return bpufirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.bpufirst
	 * @param bpufirst  the value for RdRecord.bpufirst
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setBpufirst(Boolean bpufirst) {
		this.bpufirst = bpufirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.biafirst
	 * @return  the value of RdRecord.biafirst
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Boolean getBiafirst() {
		return biafirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.biafirst
	 * @param biafirst  the value for RdRecord.biafirst
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setBiafirst(Boolean biafirst) {
		this.biafirst = biafirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.iMQuantity
	 * @return  the value of RdRecord.iMQuantity
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Double getImquantity() {
		return imquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.iMQuantity
	 * @param imquantity  the value for RdRecord.iMQuantity
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setImquantity(Double imquantity) {
		this.imquantity = imquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.dARVDate
	 * @return  the value of RdRecord.dARVDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Date getDarvdate() {
		return darvdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.dARVDate
	 * @param darvdate  the value for RdRecord.dARVDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setDarvdate(Date darvdate) {
		this.darvdate = darvdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cChkCode
	 * @return  the value of RdRecord.cChkCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCchkcode() {
		return cchkcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cChkCode
	 * @param cchkcode  the value for RdRecord.cChkCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCchkcode(String cchkcode) {
		this.cchkcode = cchkcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.dChkDate
	 * @return  the value of RdRecord.dChkDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Date getDchkdate() {
		return dchkdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.dChkDate
	 * @param dchkdate  the value for RdRecord.dChkDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setDchkdate(Date dchkdate) {
		this.dchkdate = dchkdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cChkPerson
	 * @return  the value of RdRecord.cChkPerson
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCchkperson() {
		return cchkperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cChkPerson
	 * @param cchkperson  the value for RdRecord.cChkPerson
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCchkperson(String cchkperson) {
		this.cchkperson = cchkperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.VT_ID
	 * @return  the value of RdRecord.VT_ID
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getVtId() {
		return vtId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.VT_ID
	 * @param vtId  the value for RdRecord.VT_ID
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setVtId(Integer vtId) {
		this.vtId = vtId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.bIsSTQc
	 * @return  the value of RdRecord.bIsSTQc
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Boolean getBisstqc() {
		return bisstqc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.bIsSTQc
	 * @param bisstqc  the value for RdRecord.bIsSTQc
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setBisstqc(Boolean bisstqc) {
		this.bisstqc = bisstqc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine11
	 * @return  the value of RdRecord.cDefine11
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine11() {
		return cdefine11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine11
	 * @param cdefine11  the value for RdRecord.cDefine11
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine11(String cdefine11) {
		this.cdefine11 = cdefine11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine12
	 * @return  the value of RdRecord.cDefine12
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine12() {
		return cdefine12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine12
	 * @param cdefine12  the value for RdRecord.cDefine12
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine12(String cdefine12) {
		this.cdefine12 = cdefine12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine13
	 * @return  the value of RdRecord.cDefine13
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine13() {
		return cdefine13;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine13
	 * @param cdefine13  the value for RdRecord.cDefine13
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine13(String cdefine13) {
		this.cdefine13 = cdefine13;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine14
	 * @return  the value of RdRecord.cDefine14
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCdefine14() {
		return cdefine14;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine14
	 * @param cdefine14  the value for RdRecord.cDefine14
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine14(String cdefine14) {
		this.cdefine14 = cdefine14;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine15
	 * @return  the value of RdRecord.cDefine15
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getCdefine15() {
		return cdefine15;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine15
	 * @param cdefine15  the value for RdRecord.cDefine15
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine15(Integer cdefine15) {
		this.cdefine15 = cdefine15;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cDefine16
	 * @return  the value of RdRecord.cDefine16
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Double getCdefine16() {
		return cdefine16;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cDefine16
	 * @param cdefine16  the value for RdRecord.cDefine16
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCdefine16(Double cdefine16) {
		this.cdefine16 = cdefine16;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cPsPcode
	 * @return  the value of RdRecord.cPsPcode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCpspcode() {
		return cpspcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cPsPcode
	 * @param cpspcode  the value for RdRecord.cPsPcode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCpspcode(String cpspcode) {
		this.cpspcode = cpspcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cMPoCode
	 * @return  the value of RdRecord.cMPoCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCmpocode() {
		return cmpocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cMPoCode
	 * @param cmpocode  the value for RdRecord.cMPoCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCmpocode(String cmpocode) {
		this.cmpocode = cmpocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.gspcheck
	 * @return  the value of RdRecord.gspcheck
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getGspcheck() {
		return gspcheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.gspcheck
	 * @param gspcheck  the value for RdRecord.gspcheck
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setGspcheck(String gspcheck) {
		this.gspcheck = gspcheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.ipurorderid
	 * @return  the value of RdRecord.ipurorderid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getIpurorderid() {
		return ipurorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.ipurorderid
	 * @param ipurorderid  the value for RdRecord.ipurorderid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setIpurorderid(Integer ipurorderid) {
		this.ipurorderid = ipurorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.ipurarriveid
	 * @return  the value of RdRecord.ipurarriveid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getIpurarriveid() {
		return ipurarriveid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.ipurarriveid
	 * @param ipurarriveid  the value for RdRecord.ipurarriveid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setIpurarriveid(Integer ipurarriveid) {
		this.ipurarriveid = ipurarriveid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.iproorderid
	 * @return  the value of RdRecord.iproorderid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Integer getIproorderid() {
		return iproorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.iproorderid
	 * @param iproorderid  the value for RdRecord.iproorderid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setIproorderid(Integer iproorderid) {
		this.iproorderid = iproorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.iarriveid
	 * @return  the value of RdRecord.iarriveid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getIarriveid() {
		return iarriveid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.iarriveid
	 * @param iarriveid  the value for RdRecord.iarriveid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setIarriveid(String iarriveid) {
		this.iarriveid = iarriveid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.isalebillid
	 * @return  the value of RdRecord.isalebillid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getIsalebillid() {
		return isalebillid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.isalebillid
	 * @param isalebillid  the value for RdRecord.isalebillid
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setIsalebillid(String isalebillid) {
		this.isalebillid = isalebillid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cBomSoCode
	 * @return  the value of RdRecord.cBomSoCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCbomsocode() {
		return cbomsocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cBomSoCode
	 * @param cbomsocode  the value for RdRecord.cBomSoCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCbomsocode(String cbomsocode) {
		this.cbomsocode = cbomsocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cOMrdType
	 * @return  the value of RdRecord.cOMrdType
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getComrdtype() {
		return comrdtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cOMrdType
	 * @param comrdtype  the value for RdRecord.cOMrdType
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setComrdtype(String comrdtype) {
		this.comrdtype = comrdtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cBusCode2
	 * @return  the value of RdRecord.cBusCode2
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCbuscode2() {
		return cbuscode2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cBusCode2
	 * @param cbuscode2  the value for RdRecord.cBusCode2
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCbuscode2(String cbuscode2) {
		this.cbuscode2 = cbuscode2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.iTaxRate
	 * @return  the value of RdRecord.iTaxRate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Double getItaxrate() {
		return itaxrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.iTaxRate
	 * @param itaxrate  the value for RdRecord.iTaxRate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setItaxrate(Double itaxrate) {
		this.itaxrate = itaxrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cAccountPID
	 * @return  the value of RdRecord.cAccountPID
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCaccountpid() {
		return caccountpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cAccountPID
	 * @param caccountpid  the value for RdRecord.cAccountPID
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCaccountpid(String caccountpid) {
		this.caccountpid = caccountpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cAccountPDate
	 * @return  the value of RdRecord.cAccountPDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Date getCaccountpdate() {
		return caccountpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cAccountPDate
	 * @param caccountpdate  the value for RdRecord.cAccountPDate
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCaccountpdate(Date caccountpdate) {
		this.caccountpdate = caccountpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cPayCode
	 * @return  the value of RdRecord.cPayCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCpaycode() {
		return cpaycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cPayCode
	 * @param cpaycode  the value for RdRecord.cPayCode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCpaycode(String cpaycode) {
		this.cpaycode = cpaycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.bgxljz
	 * @return  the value of RdRecord.bgxljz
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Boolean getBgxljz() {
		return bgxljz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.bgxljz
	 * @param bgxljz  the value for RdRecord.bgxljz
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setBgxljz(Boolean bgxljz) {
		this.bgxljz = bgxljz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.bisomqc
	 * @return  the value of RdRecord.bisomqc
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public Boolean getBisomqc() {
		return bisomqc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.bisomqc
	 * @param bisomqc  the value for RdRecord.bisomqc
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setBisomqc(Boolean bisomqc) {
		this.bisomqc = bisomqc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cvenbank
	 * @return  the value of RdRecord.cvenbank
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvenbank() {
		return cvenbank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cvenbank
	 * @param cvenbank  the value for RdRecord.cvenbank
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvenbank(String cvenbank) {
		this.cvenbank = cvenbank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cvenaddress
	 * @return  the value of RdRecord.cvenaddress
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvenaddress() {
		return cvenaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cvenaddress
	 * @param cvenaddress  the value for RdRecord.cvenaddress
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvenaddress(String cvenaddress) {
		this.cvenaddress = cvenaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cvenphone
	 * @return  the value of RdRecord.cvenphone
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvenphone() {
		return cvenphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cvenphone
	 * @param cvenphone  the value for RdRecord.cvenphone
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvenphone(String cvenphone) {
		this.cvenphone = cvenphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cvenfax
	 * @return  the value of RdRecord.cvenfax
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvenfax() {
		return cvenfax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cvenfax
	 * @param cvenfax  the value for RdRecord.cvenfax
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvenfax(String cvenfax) {
		this.cvenfax = cvenfax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cvenpostcode
	 * @return  the value of RdRecord.cvenpostcode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvenpostcode() {
		return cvenpostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cvenpostcode
	 * @param cvenpostcode  the value for RdRecord.cvenpostcode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvenpostcode(String cvenpostcode) {
		this.cvenpostcode = cvenpostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cvenperson
	 * @return  the value of RdRecord.cvenperson
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvenperson() {
		return cvenperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cvenperson
	 * @param cvenperson  the value for RdRecord.cvenperson
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvenperson(String cvenperson) {
		this.cvenperson = cvenperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cvenaccount
	 * @return  the value of RdRecord.cvenaccount
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvenaccount() {
		return cvenaccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cvenaccount
	 * @param cvenaccount  the value for RdRecord.cvenaccount
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvenaccount(String cvenaccount) {
		this.cvenaccount = cvenaccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.cvenregcode
	 * @return  the value of RdRecord.cvenregcode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public String getCvenregcode() {
		return cvenregcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.cvenregcode
	 * @param cvenregcode  the value for RdRecord.cvenregcode
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setCvenregcode(String cvenregcode) {
		this.cvenregcode = cvenregcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RdRecord.ufts
	 * @return  the value of RdRecord.ufts
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public byte[] getUfts() {
		return ufts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RdRecord.ufts
	 * @param ufts  the value for RdRecord.ufts
	 * @mbggenerated  Sun Sep 13 17:00:26 CST 2015
	 */
	public void setUfts(byte[] ufts) {
		this.ufts = ufts;
	}
}