package eclipse;

import java.util.Date;

public class Transvouch  extends BaseObj{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cTVCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String ctvcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.dTVDate
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Date dtvdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cOWhCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cowhcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cIWhCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String ciwhcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cODepCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String codepcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cIDepCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cidepcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cPersonCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cpersoncode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cIRdCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cirdcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cORdCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cordcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cTVMemo
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String ctvmemo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine1
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine2
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine3
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine4
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Date cdefine4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine5
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Integer cdefine5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine6
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Date cdefine6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine7
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Double cdefine7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine8
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine9
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine10
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cAccounter
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String caccounter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cMaker
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cmaker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.iNetLock
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Float inetlock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.ID
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.VT_ID
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Integer vtId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cVerifyPerson
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cverifyperson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.dVerifyDate
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Date dverifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cPSPCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cpspcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cMPoCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cmpocode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.iQuantity
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Double iquantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.bTransFlag
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Boolean btransflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine11
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine11;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine12
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine12;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine13
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine13;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine14
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private String cdefine14;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine15
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Integer cdefine15;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.cDefine16
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Double cdefine16;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.iproorderid
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private Integer iproorderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TransVouch.ufts
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	private byte[] ufts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cTVCode
	 * @return  the value of dbo.TransVouch.cTVCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCtvcode() {
		return ctvcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cTVCode
	 * @param ctvcode  the value for dbo.TransVouch.cTVCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCtvcode(String ctvcode) {
		this.ctvcode = ctvcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.dTVDate
	 * @return  the value of dbo.TransVouch.dTVDate
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Date getDtvdate() {
		return dtvdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.dTVDate
	 * @param dtvdate  the value for dbo.TransVouch.dTVDate
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setDtvdate(Date dtvdate) {
		this.dtvdate = dtvdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cOWhCode
	 * @return  the value of dbo.TransVouch.cOWhCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCowhcode() {
		return cowhcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cOWhCode
	 * @param cowhcode  the value for dbo.TransVouch.cOWhCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCowhcode(String cowhcode) {
		this.cowhcode = cowhcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cIWhCode
	 * @return  the value of dbo.TransVouch.cIWhCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCiwhcode() {
		return ciwhcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cIWhCode
	 * @param ciwhcode  the value for dbo.TransVouch.cIWhCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCiwhcode(String ciwhcode) {
		this.ciwhcode = ciwhcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cODepCode
	 * @return  the value of dbo.TransVouch.cODepCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCodepcode() {
		return codepcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cODepCode
	 * @param codepcode  the value for dbo.TransVouch.cODepCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCodepcode(String codepcode) {
		this.codepcode = codepcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cIDepCode
	 * @return  the value of dbo.TransVouch.cIDepCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCidepcode() {
		return cidepcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cIDepCode
	 * @param cidepcode  the value for dbo.TransVouch.cIDepCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCidepcode(String cidepcode) {
		this.cidepcode = cidepcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cPersonCode
	 * @return  the value of dbo.TransVouch.cPersonCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCpersoncode() {
		return cpersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cPersonCode
	 * @param cpersoncode  the value for dbo.TransVouch.cPersonCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCpersoncode(String cpersoncode) {
		this.cpersoncode = cpersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cIRdCode
	 * @return  the value of dbo.TransVouch.cIRdCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCirdcode() {
		return cirdcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cIRdCode
	 * @param cirdcode  the value for dbo.TransVouch.cIRdCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCirdcode(String cirdcode) {
		this.cirdcode = cirdcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cORdCode
	 * @return  the value of dbo.TransVouch.cORdCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCordcode() {
		return cordcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cORdCode
	 * @param cordcode  the value for dbo.TransVouch.cORdCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCordcode(String cordcode) {
		this.cordcode = cordcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cTVMemo
	 * @return  the value of dbo.TransVouch.cTVMemo
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCtvmemo() {
		return ctvmemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cTVMemo
	 * @param ctvmemo  the value for dbo.TransVouch.cTVMemo
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCtvmemo(String ctvmemo) {
		this.ctvmemo = ctvmemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine1
	 * @return  the value of dbo.TransVouch.cDefine1
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine1() {
		return cdefine1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine1
	 * @param cdefine1  the value for dbo.TransVouch.cDefine1
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine1(String cdefine1) {
		this.cdefine1 = cdefine1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine2
	 * @return  the value of dbo.TransVouch.cDefine2
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine2() {
		return cdefine2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine2
	 * @param cdefine2  the value for dbo.TransVouch.cDefine2
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine2(String cdefine2) {
		this.cdefine2 = cdefine2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine3
	 * @return  the value of dbo.TransVouch.cDefine3
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine3() {
		return cdefine3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine3
	 * @param cdefine3  the value for dbo.TransVouch.cDefine3
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine3(String cdefine3) {
		this.cdefine3 = cdefine3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine4
	 * @return  the value of dbo.TransVouch.cDefine4
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Date getCdefine4() {
		return cdefine4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine4
	 * @param cdefine4  the value for dbo.TransVouch.cDefine4
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine4(Date cdefine4) {
		this.cdefine4 = cdefine4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine5
	 * @return  the value of dbo.TransVouch.cDefine5
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Integer getCdefine5() {
		return cdefine5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine5
	 * @param cdefine5  the value for dbo.TransVouch.cDefine5
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine5(Integer cdefine5) {
		this.cdefine5 = cdefine5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine6
	 * @return  the value of dbo.TransVouch.cDefine6
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Date getCdefine6() {
		return cdefine6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine6
	 * @param cdefine6  the value for dbo.TransVouch.cDefine6
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine6(Date cdefine6) {
		this.cdefine6 = cdefine6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine7
	 * @return  the value of dbo.TransVouch.cDefine7
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Double getCdefine7() {
		return cdefine7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine7
	 * @param cdefine7  the value for dbo.TransVouch.cDefine7
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine7(Double cdefine7) {
		this.cdefine7 = cdefine7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine8
	 * @return  the value of dbo.TransVouch.cDefine8
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine8() {
		return cdefine8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine8
	 * @param cdefine8  the value for dbo.TransVouch.cDefine8
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine8(String cdefine8) {
		this.cdefine8 = cdefine8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine9
	 * @return  the value of dbo.TransVouch.cDefine9
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine9() {
		return cdefine9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine9
	 * @param cdefine9  the value for dbo.TransVouch.cDefine9
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine9(String cdefine9) {
		this.cdefine9 = cdefine9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine10
	 * @return  the value of dbo.TransVouch.cDefine10
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine10() {
		return cdefine10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine10
	 * @param cdefine10  the value for dbo.TransVouch.cDefine10
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine10(String cdefine10) {
		this.cdefine10 = cdefine10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cAccounter
	 * @return  the value of dbo.TransVouch.cAccounter
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCaccounter() {
		return caccounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cAccounter
	 * @param caccounter  the value for dbo.TransVouch.cAccounter
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCaccounter(String caccounter) {
		this.caccounter = caccounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cMaker
	 * @return  the value of dbo.TransVouch.cMaker
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCmaker() {
		return cmaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cMaker
	 * @param cmaker  the value for dbo.TransVouch.cMaker
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCmaker(String cmaker) {
		this.cmaker = cmaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.iNetLock
	 * @return  the value of dbo.TransVouch.iNetLock
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Float getInetlock() {
		return inetlock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.iNetLock
	 * @param inetlock  the value for dbo.TransVouch.iNetLock
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setInetlock(Float inetlock) {
		this.inetlock = inetlock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.ID
	 * @return  the value of dbo.TransVouch.ID
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.ID
	 * @param id  the value for dbo.TransVouch.ID
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.VT_ID
	 * @return  the value of dbo.TransVouch.VT_ID
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Integer getVtId() {
		return vtId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.VT_ID
	 * @param vtId  the value for dbo.TransVouch.VT_ID
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setVtId(Integer vtId) {
		this.vtId = vtId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cVerifyPerson
	 * @return  the value of dbo.TransVouch.cVerifyPerson
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCverifyperson() {
		return cverifyperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cVerifyPerson
	 * @param cverifyperson  the value for dbo.TransVouch.cVerifyPerson
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCverifyperson(String cverifyperson) {
		this.cverifyperson = cverifyperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.dVerifyDate
	 * @return  the value of dbo.TransVouch.dVerifyDate
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Date getDverifydate() {
		return dverifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.dVerifyDate
	 * @param dverifydate  the value for dbo.TransVouch.dVerifyDate
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setDverifydate(Date dverifydate) {
		this.dverifydate = dverifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cPSPCode
	 * @return  the value of dbo.TransVouch.cPSPCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCpspcode() {
		return cpspcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cPSPCode
	 * @param cpspcode  the value for dbo.TransVouch.cPSPCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCpspcode(String cpspcode) {
		this.cpspcode = cpspcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cMPoCode
	 * @return  the value of dbo.TransVouch.cMPoCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCmpocode() {
		return cmpocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cMPoCode
	 * @param cmpocode  the value for dbo.TransVouch.cMPoCode
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCmpocode(String cmpocode) {
		this.cmpocode = cmpocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.iQuantity
	 * @return  the value of dbo.TransVouch.iQuantity
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Double getIquantity() {
		return iquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.iQuantity
	 * @param iquantity  the value for dbo.TransVouch.iQuantity
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setIquantity(Double iquantity) {
		this.iquantity = iquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.bTransFlag
	 * @return  the value of dbo.TransVouch.bTransFlag
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Boolean getBtransflag() {
		return btransflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.bTransFlag
	 * @param btransflag  the value for dbo.TransVouch.bTransFlag
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setBtransflag(Boolean btransflag) {
		this.btransflag = btransflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine11
	 * @return  the value of dbo.TransVouch.cDefine11
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine11() {
		return cdefine11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine11
	 * @param cdefine11  the value for dbo.TransVouch.cDefine11
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine11(String cdefine11) {
		this.cdefine11 = cdefine11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine12
	 * @return  the value of dbo.TransVouch.cDefine12
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine12() {
		return cdefine12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine12
	 * @param cdefine12  the value for dbo.TransVouch.cDefine12
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine12(String cdefine12) {
		this.cdefine12 = cdefine12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine13
	 * @return  the value of dbo.TransVouch.cDefine13
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine13() {
		return cdefine13;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine13
	 * @param cdefine13  the value for dbo.TransVouch.cDefine13
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine13(String cdefine13) {
		this.cdefine13 = cdefine13;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine14
	 * @return  the value of dbo.TransVouch.cDefine14
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public String getCdefine14() {
		return cdefine14;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine14
	 * @param cdefine14  the value for dbo.TransVouch.cDefine14
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine14(String cdefine14) {
		this.cdefine14 = cdefine14;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine15
	 * @return  the value of dbo.TransVouch.cDefine15
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Integer getCdefine15() {
		return cdefine15;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine15
	 * @param cdefine15  the value for dbo.TransVouch.cDefine15
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine15(Integer cdefine15) {
		this.cdefine15 = cdefine15;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.cDefine16
	 * @return  the value of dbo.TransVouch.cDefine16
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Double getCdefine16() {
		return cdefine16;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.cDefine16
	 * @param cdefine16  the value for dbo.TransVouch.cDefine16
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setCdefine16(Double cdefine16) {
		this.cdefine16 = cdefine16;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.iproorderid
	 * @return  the value of dbo.TransVouch.iproorderid
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public Integer getIproorderid() {
		return iproorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.iproorderid
	 * @param iproorderid  the value for dbo.TransVouch.iproorderid
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setIproorderid(Integer iproorderid) {
		this.iproorderid = iproorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TransVouch.ufts
	 * @return  the value of dbo.TransVouch.ufts
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public byte[] getUfts() {
		return ufts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TransVouch.ufts
	 * @param ufts  the value for dbo.TransVouch.ufts
	 * @mbggenerated  Tue Nov 17 23:53:09 CST 2015
	 */
	public void setUfts(byte[] ufts) {
		this.ufts = ufts;
	}
}