package eclipse;

import java.util.Date;

public class Transvouchs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.autoID
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Integer autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cTVCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String ctvcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cInvCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cinvcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.RdsID
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Integer rdsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.iTVNum
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double itvnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.iTVQuantity
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double itvquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.iTVACost
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double itvacost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.iTVAPrice
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double itvaprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.iTVPCost
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double itvpcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.iTVPPrice
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double itvpprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cTVBatch
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String ctvbatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.dDisDate
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Date ddisdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree1
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree2
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine22
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine23
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine24
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine25
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine26
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double cdefine26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine27
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double cdefine27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cItemCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String citemcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cItem_class
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String citemClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.fSaleCost
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double fsalecost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.fSalePrice
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Double fsaleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cName
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cItemCName
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String citemcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.ID
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.iMassDate
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Integer imassdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cBarCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cbarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cAssUnit
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cassunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree3
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree4
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree5
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree6
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree7
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree8
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree9
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cFree10
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cfree10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine28
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine29
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine30
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine31
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine31;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine32
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine32;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine33
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cdefine33;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine34
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Integer cdefine34;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine35
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Integer cdefine35;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine36
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Date cdefine36;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cDefine37
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Date cdefine37;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.iMPoIds
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Integer impoids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cBVencode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cbvencode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cInVouchCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cinvouchcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.dMadeDate
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private Date dmadedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.coutposcode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String coutposcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TransVouchs.cinposcode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    private String cinposcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.autoID
     *
     * @return the value of dbo.TransVouchs.autoID
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Integer getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.autoID
     *
     * @param autoid the value for dbo.TransVouchs.autoID
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setAutoid(Integer autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cTVCode
     *
     * @return the value of dbo.TransVouchs.cTVCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCtvcode() {
        return ctvcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cTVCode
     *
     * @param ctvcode the value for dbo.TransVouchs.cTVCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCtvcode(String ctvcode) {
        this.ctvcode = ctvcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cInvCode
     *
     * @return the value of dbo.TransVouchs.cInvCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCinvcode() {
        return cinvcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cInvCode
     *
     * @param cinvcode the value for dbo.TransVouchs.cInvCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCinvcode(String cinvcode) {
        this.cinvcode = cinvcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.RdsID
     *
     * @return the value of dbo.TransVouchs.RdsID
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Integer getRdsid() {
        return rdsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.RdsID
     *
     * @param rdsid the value for dbo.TransVouchs.RdsID
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setRdsid(Integer rdsid) {
        this.rdsid = rdsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.iTVNum
     *
     * @return the value of dbo.TransVouchs.iTVNum
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getItvnum() {
        return itvnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.iTVNum
     *
     * @param itvnum the value for dbo.TransVouchs.iTVNum
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setItvnum(Double itvnum) {
        this.itvnum = itvnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.iTVQuantity
     *
     * @return the value of dbo.TransVouchs.iTVQuantity
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getItvquantity() {
        return itvquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.iTVQuantity
     *
     * @param itvquantity the value for dbo.TransVouchs.iTVQuantity
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setItvquantity(Double itvquantity) {
        this.itvquantity = itvquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.iTVACost
     *
     * @return the value of dbo.TransVouchs.iTVACost
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getItvacost() {
        return itvacost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.iTVACost
     *
     * @param itvacost the value for dbo.TransVouchs.iTVACost
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setItvacost(Double itvacost) {
        this.itvacost = itvacost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.iTVAPrice
     *
     * @return the value of dbo.TransVouchs.iTVAPrice
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getItvaprice() {
        return itvaprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.iTVAPrice
     *
     * @param itvaprice the value for dbo.TransVouchs.iTVAPrice
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setItvaprice(Double itvaprice) {
        this.itvaprice = itvaprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.iTVPCost
     *
     * @return the value of dbo.TransVouchs.iTVPCost
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getItvpcost() {
        return itvpcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.iTVPCost
     *
     * @param itvpcost the value for dbo.TransVouchs.iTVPCost
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setItvpcost(Double itvpcost) {
        this.itvpcost = itvpcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.iTVPPrice
     *
     * @return the value of dbo.TransVouchs.iTVPPrice
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getItvpprice() {
        return itvpprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.iTVPPrice
     *
     * @param itvpprice the value for dbo.TransVouchs.iTVPPrice
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setItvpprice(Double itvpprice) {
        this.itvpprice = itvpprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cTVBatch
     *
     * @return the value of dbo.TransVouchs.cTVBatch
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCtvbatch() {
        return ctvbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cTVBatch
     *
     * @param ctvbatch the value for dbo.TransVouchs.cTVBatch
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCtvbatch(String ctvbatch) {
        this.ctvbatch = ctvbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.dDisDate
     *
     * @return the value of dbo.TransVouchs.dDisDate
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Date getDdisdate() {
        return ddisdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.dDisDate
     *
     * @param ddisdate the value for dbo.TransVouchs.dDisDate
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setDdisdate(Date ddisdate) {
        this.ddisdate = ddisdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree1
     *
     * @return the value of dbo.TransVouchs.cFree1
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree1() {
        return cfree1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree1
     *
     * @param cfree1 the value for dbo.TransVouchs.cFree1
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree1(String cfree1) {
        this.cfree1 = cfree1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree2
     *
     * @return the value of dbo.TransVouchs.cFree2
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree2() {
        return cfree2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree2
     *
     * @param cfree2 the value for dbo.TransVouchs.cFree2
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree2(String cfree2) {
        this.cfree2 = cfree2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine22
     *
     * @return the value of dbo.TransVouchs.cDefine22
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine22() {
        return cdefine22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine22
     *
     * @param cdefine22 the value for dbo.TransVouchs.cDefine22
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine22(String cdefine22) {
        this.cdefine22 = cdefine22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine23
     *
     * @return the value of dbo.TransVouchs.cDefine23
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine23() {
        return cdefine23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine23
     *
     * @param cdefine23 the value for dbo.TransVouchs.cDefine23
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine23(String cdefine23) {
        this.cdefine23 = cdefine23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine24
     *
     * @return the value of dbo.TransVouchs.cDefine24
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine24() {
        return cdefine24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine24
     *
     * @param cdefine24 the value for dbo.TransVouchs.cDefine24
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine24(String cdefine24) {
        this.cdefine24 = cdefine24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine25
     *
     * @return the value of dbo.TransVouchs.cDefine25
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine25() {
        return cdefine25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine25
     *
     * @param cdefine25 the value for dbo.TransVouchs.cDefine25
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine25(String cdefine25) {
        this.cdefine25 = cdefine25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine26
     *
     * @return the value of dbo.TransVouchs.cDefine26
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getCdefine26() {
        return cdefine26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine26
     *
     * @param cdefine26 the value for dbo.TransVouchs.cDefine26
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine26(Double cdefine26) {
        this.cdefine26 = cdefine26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine27
     *
     * @return the value of dbo.TransVouchs.cDefine27
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getCdefine27() {
        return cdefine27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine27
     *
     * @param cdefine27 the value for dbo.TransVouchs.cDefine27
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine27(Double cdefine27) {
        this.cdefine27 = cdefine27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cItemCode
     *
     * @return the value of dbo.TransVouchs.cItemCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCitemcode() {
        return citemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cItemCode
     *
     * @param citemcode the value for dbo.TransVouchs.cItemCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCitemcode(String citemcode) {
        this.citemcode = citemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cItem_class
     *
     * @return the value of dbo.TransVouchs.cItem_class
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCitemClass() {
        return citemClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cItem_class
     *
     * @param citemClass the value for dbo.TransVouchs.cItem_class
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCitemClass(String citemClass) {
        this.citemClass = citemClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.fSaleCost
     *
     * @return the value of dbo.TransVouchs.fSaleCost
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getFsalecost() {
        return fsalecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.fSaleCost
     *
     * @param fsalecost the value for dbo.TransVouchs.fSaleCost
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setFsalecost(Double fsalecost) {
        this.fsalecost = fsalecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.fSalePrice
     *
     * @return the value of dbo.TransVouchs.fSalePrice
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Double getFsaleprice() {
        return fsaleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.fSalePrice
     *
     * @param fsaleprice the value for dbo.TransVouchs.fSalePrice
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setFsaleprice(Double fsaleprice) {
        this.fsaleprice = fsaleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cName
     *
     * @return the value of dbo.TransVouchs.cName
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cName
     *
     * @param cname the value for dbo.TransVouchs.cName
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cItemCName
     *
     * @return the value of dbo.TransVouchs.cItemCName
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCitemcname() {
        return citemcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cItemCName
     *
     * @param citemcname the value for dbo.TransVouchs.cItemCName
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCitemcname(String citemcname) {
        this.citemcname = citemcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.ID
     *
     * @return the value of dbo.TransVouchs.ID
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.ID
     *
     * @param id the value for dbo.TransVouchs.ID
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.iMassDate
     *
     * @return the value of dbo.TransVouchs.iMassDate
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Integer getImassdate() {
        return imassdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.iMassDate
     *
     * @param imassdate the value for dbo.TransVouchs.iMassDate
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setImassdate(Integer imassdate) {
        this.imassdate = imassdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cBarCode
     *
     * @return the value of dbo.TransVouchs.cBarCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCbarcode() {
        return cbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cBarCode
     *
     * @param cbarcode the value for dbo.TransVouchs.cBarCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCbarcode(String cbarcode) {
        this.cbarcode = cbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cAssUnit
     *
     * @return the value of dbo.TransVouchs.cAssUnit
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCassunit() {
        return cassunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cAssUnit
     *
     * @param cassunit the value for dbo.TransVouchs.cAssUnit
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCassunit(String cassunit) {
        this.cassunit = cassunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree3
     *
     * @return the value of dbo.TransVouchs.cFree3
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree3() {
        return cfree3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree3
     *
     * @param cfree3 the value for dbo.TransVouchs.cFree3
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree3(String cfree3) {
        this.cfree3 = cfree3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree4
     *
     * @return the value of dbo.TransVouchs.cFree4
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree4() {
        return cfree4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree4
     *
     * @param cfree4 the value for dbo.TransVouchs.cFree4
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree4(String cfree4) {
        this.cfree4 = cfree4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree5
     *
     * @return the value of dbo.TransVouchs.cFree5
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree5() {
        return cfree5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree5
     *
     * @param cfree5 the value for dbo.TransVouchs.cFree5
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree5(String cfree5) {
        this.cfree5 = cfree5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree6
     *
     * @return the value of dbo.TransVouchs.cFree6
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree6() {
        return cfree6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree6
     *
     * @param cfree6 the value for dbo.TransVouchs.cFree6
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree6(String cfree6) {
        this.cfree6 = cfree6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree7
     *
     * @return the value of dbo.TransVouchs.cFree7
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree7() {
        return cfree7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree7
     *
     * @param cfree7 the value for dbo.TransVouchs.cFree7
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree7(String cfree7) {
        this.cfree7 = cfree7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree8
     *
     * @return the value of dbo.TransVouchs.cFree8
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree8() {
        return cfree8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree8
     *
     * @param cfree8 the value for dbo.TransVouchs.cFree8
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree8(String cfree8) {
        this.cfree8 = cfree8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree9
     *
     * @return the value of dbo.TransVouchs.cFree9
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree9() {
        return cfree9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree9
     *
     * @param cfree9 the value for dbo.TransVouchs.cFree9
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree9(String cfree9) {
        this.cfree9 = cfree9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cFree10
     *
     * @return the value of dbo.TransVouchs.cFree10
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCfree10() {
        return cfree10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cFree10
     *
     * @param cfree10 the value for dbo.TransVouchs.cFree10
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCfree10(String cfree10) {
        this.cfree10 = cfree10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine28
     *
     * @return the value of dbo.TransVouchs.cDefine28
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine28() {
        return cdefine28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine28
     *
     * @param cdefine28 the value for dbo.TransVouchs.cDefine28
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine28(String cdefine28) {
        this.cdefine28 = cdefine28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine29
     *
     * @return the value of dbo.TransVouchs.cDefine29
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine29() {
        return cdefine29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine29
     *
     * @param cdefine29 the value for dbo.TransVouchs.cDefine29
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine29(String cdefine29) {
        this.cdefine29 = cdefine29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine30
     *
     * @return the value of dbo.TransVouchs.cDefine30
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine30() {
        return cdefine30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine30
     *
     * @param cdefine30 the value for dbo.TransVouchs.cDefine30
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine30(String cdefine30) {
        this.cdefine30 = cdefine30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine31
     *
     * @return the value of dbo.TransVouchs.cDefine31
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine31() {
        return cdefine31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine31
     *
     * @param cdefine31 the value for dbo.TransVouchs.cDefine31
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine31(String cdefine31) {
        this.cdefine31 = cdefine31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine32
     *
     * @return the value of dbo.TransVouchs.cDefine32
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine32() {
        return cdefine32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine32
     *
     * @param cdefine32 the value for dbo.TransVouchs.cDefine32
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine32(String cdefine32) {
        this.cdefine32 = cdefine32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine33
     *
     * @return the value of dbo.TransVouchs.cDefine33
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCdefine33() {
        return cdefine33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine33
     *
     * @param cdefine33 the value for dbo.TransVouchs.cDefine33
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine33(String cdefine33) {
        this.cdefine33 = cdefine33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine34
     *
     * @return the value of dbo.TransVouchs.cDefine34
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Integer getCdefine34() {
        return cdefine34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine34
     *
     * @param cdefine34 the value for dbo.TransVouchs.cDefine34
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine34(Integer cdefine34) {
        this.cdefine34 = cdefine34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine35
     *
     * @return the value of dbo.TransVouchs.cDefine35
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Integer getCdefine35() {
        return cdefine35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine35
     *
     * @param cdefine35 the value for dbo.TransVouchs.cDefine35
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine35(Integer cdefine35) {
        this.cdefine35 = cdefine35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine36
     *
     * @return the value of dbo.TransVouchs.cDefine36
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Date getCdefine36() {
        return cdefine36;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine36
     *
     * @param cdefine36 the value for dbo.TransVouchs.cDefine36
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine36(Date cdefine36) {
        this.cdefine36 = cdefine36;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cDefine37
     *
     * @return the value of dbo.TransVouchs.cDefine37
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Date getCdefine37() {
        return cdefine37;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cDefine37
     *
     * @param cdefine37 the value for dbo.TransVouchs.cDefine37
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCdefine37(Date cdefine37) {
        this.cdefine37 = cdefine37;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.iMPoIds
     *
     * @return the value of dbo.TransVouchs.iMPoIds
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Integer getImpoids() {
        return impoids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.iMPoIds
     *
     * @param impoids the value for dbo.TransVouchs.iMPoIds
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setImpoids(Integer impoids) {
        this.impoids = impoids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cBVencode
     *
     * @return the value of dbo.TransVouchs.cBVencode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCbvencode() {
        return cbvencode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cBVencode
     *
     * @param cbvencode the value for dbo.TransVouchs.cBVencode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCbvencode(String cbvencode) {
        this.cbvencode = cbvencode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cInVouchCode
     *
     * @return the value of dbo.TransVouchs.cInVouchCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCinvouchcode() {
        return cinvouchcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cInVouchCode
     *
     * @param cinvouchcode the value for dbo.TransVouchs.cInVouchCode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCinvouchcode(String cinvouchcode) {
        this.cinvouchcode = cinvouchcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.dMadeDate
     *
     * @return the value of dbo.TransVouchs.dMadeDate
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public Date getDmadedate() {
        return dmadedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.dMadeDate
     *
     * @param dmadedate the value for dbo.TransVouchs.dMadeDate
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setDmadedate(Date dmadedate) {
        this.dmadedate = dmadedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.coutposcode
     *
     * @return the value of dbo.TransVouchs.coutposcode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCoutposcode() {
        return coutposcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.coutposcode
     *
     * @param coutposcode the value for dbo.TransVouchs.coutposcode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCoutposcode(String coutposcode) {
        this.coutposcode = coutposcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TransVouchs.cinposcode
     *
     * @return the value of dbo.TransVouchs.cinposcode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public String getCinposcode() {
        return cinposcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TransVouchs.cinposcode
     *
     * @param cinposcode the value for dbo.TransVouchs.cinposcode
     *
     * @mbggenerated Tue Nov 17 23:07:58 CST 2015
     */
    public void setCinposcode(String cinposcode) {
        this.cinposcode = cinposcode;
    }
}