package eclipse;

public class Warehouse {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cWhCode
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cwhcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cWhName
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cwhname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cDepCode
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cdepcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cWhAddress
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cwhaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cWhPhone
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cwhphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cWhPerson
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cwhperson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cWhValueStyle
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cwhvaluestyle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.bWhPos
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private Boolean bwhpos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.iWhFundQuota
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private Double iwhfundquota;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cMonth
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cmonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cWhMemo
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cwhmemo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.bFreeze
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private Boolean bfreeze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.cBarCode
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private String cbarcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.bMRP
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private Boolean bmrp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.bROP
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private Boolean brop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.iWHProperty
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private Short iwhproperty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.Yn
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private Boolean yn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Warehouse.pubufts
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	private byte[] pubufts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cWhCode
	 * @return  the value of dbo.Warehouse.cWhCode
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCwhcode() {
		return cwhcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cWhCode
	 * @param cwhcode  the value for dbo.Warehouse.cWhCode
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCwhcode(String cwhcode) {
		this.cwhcode = cwhcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cWhName
	 * @return  the value of dbo.Warehouse.cWhName
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCwhname() {
		return cwhname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cWhName
	 * @param cwhname  the value for dbo.Warehouse.cWhName
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCwhname(String cwhname) {
		this.cwhname = cwhname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cDepCode
	 * @return  the value of dbo.Warehouse.cDepCode
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCdepcode() {
		return cdepcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cDepCode
	 * @param cdepcode  the value for dbo.Warehouse.cDepCode
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCdepcode(String cdepcode) {
		this.cdepcode = cdepcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cWhAddress
	 * @return  the value of dbo.Warehouse.cWhAddress
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCwhaddress() {
		return cwhaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cWhAddress
	 * @param cwhaddress  the value for dbo.Warehouse.cWhAddress
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCwhaddress(String cwhaddress) {
		this.cwhaddress = cwhaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cWhPhone
	 * @return  the value of dbo.Warehouse.cWhPhone
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCwhphone() {
		return cwhphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cWhPhone
	 * @param cwhphone  the value for dbo.Warehouse.cWhPhone
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCwhphone(String cwhphone) {
		this.cwhphone = cwhphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cWhPerson
	 * @return  the value of dbo.Warehouse.cWhPerson
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCwhperson() {
		return cwhperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cWhPerson
	 * @param cwhperson  the value for dbo.Warehouse.cWhPerson
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCwhperson(String cwhperson) {
		this.cwhperson = cwhperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cWhValueStyle
	 * @return  the value of dbo.Warehouse.cWhValueStyle
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCwhvaluestyle() {
		return cwhvaluestyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cWhValueStyle
	 * @param cwhvaluestyle  the value for dbo.Warehouse.cWhValueStyle
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCwhvaluestyle(String cwhvaluestyle) {
		this.cwhvaluestyle = cwhvaluestyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.bWhPos
	 * @return  the value of dbo.Warehouse.bWhPos
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public Boolean getBwhpos() {
		return bwhpos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.bWhPos
	 * @param bwhpos  the value for dbo.Warehouse.bWhPos
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setBwhpos(Boolean bwhpos) {
		this.bwhpos = bwhpos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.iWhFundQuota
	 * @return  the value of dbo.Warehouse.iWhFundQuota
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public Double getIwhfundquota() {
		return iwhfundquota;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.iWhFundQuota
	 * @param iwhfundquota  the value for dbo.Warehouse.iWhFundQuota
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setIwhfundquota(Double iwhfundquota) {
		this.iwhfundquota = iwhfundquota;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cMonth
	 * @return  the value of dbo.Warehouse.cMonth
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCmonth() {
		return cmonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cMonth
	 * @param cmonth  the value for dbo.Warehouse.cMonth
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCmonth(String cmonth) {
		this.cmonth = cmonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cWhMemo
	 * @return  the value of dbo.Warehouse.cWhMemo
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCwhmemo() {
		return cwhmemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cWhMemo
	 * @param cwhmemo  the value for dbo.Warehouse.cWhMemo
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCwhmemo(String cwhmemo) {
		this.cwhmemo = cwhmemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.bFreeze
	 * @return  the value of dbo.Warehouse.bFreeze
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public Boolean getBfreeze() {
		return bfreeze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.bFreeze
	 * @param bfreeze  the value for dbo.Warehouse.bFreeze
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setBfreeze(Boolean bfreeze) {
		this.bfreeze = bfreeze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.cBarCode
	 * @return  the value of dbo.Warehouse.cBarCode
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public String getCbarcode() {
		return cbarcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.cBarCode
	 * @param cbarcode  the value for dbo.Warehouse.cBarCode
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setCbarcode(String cbarcode) {
		this.cbarcode = cbarcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.bMRP
	 * @return  the value of dbo.Warehouse.bMRP
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public Boolean getBmrp() {
		return bmrp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.bMRP
	 * @param bmrp  the value for dbo.Warehouse.bMRP
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setBmrp(Boolean bmrp) {
		this.bmrp = bmrp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.bROP
	 * @return  the value of dbo.Warehouse.bROP
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public Boolean getBrop() {
		return brop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.bROP
	 * @param brop  the value for dbo.Warehouse.bROP
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setBrop(Boolean brop) {
		this.brop = brop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.iWHProperty
	 * @return  the value of dbo.Warehouse.iWHProperty
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public Short getIwhproperty() {
		return iwhproperty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.iWHProperty
	 * @param iwhproperty  the value for dbo.Warehouse.iWHProperty
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setIwhproperty(Short iwhproperty) {
		this.iwhproperty = iwhproperty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.Yn
	 * @return  the value of dbo.Warehouse.Yn
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public Boolean getYn() {
		return yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.Yn
	 * @param yn  the value for dbo.Warehouse.Yn
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setYn(Boolean yn) {
		this.yn = yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Warehouse.pubufts
	 * @return  the value of dbo.Warehouse.pubufts
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public byte[] getPubufts() {
		return pubufts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Warehouse.pubufts
	 * @param pubufts  the value for dbo.Warehouse.pubufts
	 * @mbggenerated  Sat Sep 26 21:29:42 CST 2015
	 */
	public void setPubufts(byte[] pubufts) {
		this.pubufts = pubufts;
	}
}